version: '3'
services:
  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes: 
      - "./../:/wiedza"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    # Fixing Packgist DNS Resolver
    extra_hosts:
      - "packagist.org:142.44.164.249"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes: 
      - "./../:/wiedza"
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on: 
      - "php-fpm"
    links: 
      - "php-fpm"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wiedza_password
      MYSQL_DATABASE: wiedza
      MYSQL_USER: wiedza
      MYSQL_PASSWORD: wiedza
    ports:
      - "3306:3306"
